import type { AuditEntry } from '@sigac/audit';
import type { RequestContext } from '@sigac/tenant';
import { randomUUID } from 'node:crypto';
import { Agenda } from '../domain/aggregates/Agenda.js';
import { ImportacionAgenda, type ImportacionAgendaMetrics } from '../domain/aggregates/ImportacionAgenda.js';
import type { CitaSnapshot } from '../domain/entities/Cita.js';
import { IncidenciaImportacion } from '../domain/entities/IncidenciaImportacion.js';
import { RegistroImportadoAgenda } from '../domain/entities/RegistroImportadoAgenda.js';
import type { ImportIncident, ImportOutcome, RecordProcessingResult } from '../domain/types/ImportResult.js';
import {
  ExpedienteReferencia,
  FolioCita,
  HoraCita,
  ImportacionAgendaId,
  IncidenciaImportacionId,
  PosicionRegistroOrigen,
  RegistroImportadoAgendaId,
} from '../domain/value-objects/index.js';
import type { MedicoReferencia } from '../domain/value-objects/MedicoReferencia.js';
import { ApplicationError } from './ApplicationError.js';
import type {
  AgendaFileInput,
  AgendaFileInterpreterPort,
  InterpretedAgendaFile,
  ParsedAgendaRow,
} from './ports/AgendaFileInterpreterPort.js';
import type { ExpedienteReferenceQueryPort } from './ports/ExpedienteReferenceQueryPort.js';
import type { IdempotencyKeyRepository } from './ports/IdempotencyKeyRepository.js';
import type { MedicoDirectoryQueryPort, MedicoResolution } from './ports/MedicoDirectoryQueryPort.js';
import type { AgendaPreparationUnitOfWork } from './ports/AgendaPreparationUnitOfWork.js';
import type { ImportArtifactMetadataRepository } from './ports/RepositoryPorts.js';

// ---------------------------------------------------------------------------
// Public error for structural file rejection (maps to 422 at the API boundary)
// ---------------------------------------------------------------------------

export class LayoutRejectedError extends Error {
  readonly name = 'LayoutRejectedError';
  constructor(message: string) {
    super(message);
  }
}

// ---------------------------------------------------------------------------
// Input / Output contracts
// ---------------------------------------------------------------------------

export interface ImportAgendaInput {
  /** Opaque attempt identifier generated by the boundary before authorization. */
  readonly importAttemptId: string;
  /** HTTP Idempotency-Key forwarded from the caller. */
  readonly idempotencyKey: string;
  readonly file: AgendaFileInput;
  readonly context: RequestContext;
}

export interface ImportAgendaResponse {
  readonly importacionId: string;
  readonly agendaDate: string;
  readonly outcome: ImportOutcome;
  readonly metrics: ImportacionAgendaMetrics;
  readonly hasChanges: boolean;
}

// ---------------------------------------------------------------------------
// Dependencies
// ---------------------------------------------------------------------------

export interface ImportAgendaDependencies {
  readonly interpreter: AgendaFileInterpreterPort;
  readonly medicoQuery: MedicoDirectoryQueryPort;
  readonly expedienteQuery: ExpedienteReferenceQueryPort;
  /** Pre-transaction read for fingerprint equivalence check. */
  readonly metadataRepository: ImportArtifactMetadataRepository;
  /** Pre-transaction read for idempotency key conflict detection. */
  readonly idempotencyKeyRepository: IdempotencyKeyRepository;
  readonly unitOfWork: AgendaPreparationUnitOfWork;
}

// ---------------------------------------------------------------------------
// Internal processing types
// ---------------------------------------------------------------------------

interface ResolvedRow {
  readonly row: ParsedAgendaRow;
  readonly registroId: RegistroImportadoAgendaId;
  readonly folio: FolioCita | null;
  readonly citaSnapshot: CitaSnapshot | null;
  readonly incidents: ReadonlyArray<{ readonly type: string }>;
  readonly result: RecordProcessingResult | null; // null = not yet mapped from reconciliation
}

// ---------------------------------------------------------------------------
// Use Case
// ---------------------------------------------------------------------------

export class ImportAgenda {
  constructor(private readonly deps: ImportAgendaDependencies) { }

  async execute(input: ImportAgendaInput): Promise<ImportAgendaResponse> {
    const { context } = input;
    const { tenant, actor } = context;

    // ------------------------------------------------------------------
    // 1. Authorization
    // ------------------------------------------------------------------
    if (!actor.permissions.has('AGENDA_IMPORT')) {
      // Write denied audit entry OUTSIDE the UoW (best-effort, before inspection)
      // We need an AuditWriter here — it comes from the UoW transaction, but denied
      // audits must fire even when no transaction runs.
      // Per AUTH-AP-001: denied attempt uses AGENDA_IMPORT_ATTEMPT as resourceType.
      // The AuditWriter for pre-transaction events is injected via the UoW's execute
      // mechanism only when the txn runs. For the denied case we use a dedicated
      // auditWriter that is accessible outside the transaction.
      // Design decision: re-use the UoW execute just to get the auditWriter for the
      // denied entry (single short-lived txn with no domain writes).
      await this.deps.unitOfWork.execute(tenant, async (tx) => {
        const deniedEntry: AuditEntry = {
          action: 'AGENDA_IMPORT',
          resourceType: 'AGENDA_IMPORT_ATTEMPT',
          resourceId: input.importAttemptId,
          result: 'denied',
        };
        await tx.auditWriter.append(deniedEntry, context);
      });
      throw new ApplicationError('PERMISSION_DENIED', 'El actor no tiene el permiso AGENDA_IMPORT.');
    }

    // ------------------------------------------------------------------
    // 2. Interpret file (structural validation — no audit on failure)
    // ------------------------------------------------------------------
    let interpreted: InterpretedAgendaFile;
    try {
      interpreted = await this.deps.interpreter.interpret(input.file);
    } catch (err) {
      const detail = err instanceof Error ? err.message : String(err);
      throw new LayoutRejectedError(`El archivo de Agenda no pudo ser interpretado: ${detail}`);
    }

    const { fingerprint, agendaDate } = interpreted;

    // ------------------------------------------------------------------
    // 3. Idempotency key conflict detection (pre-transaction read)
    // ------------------------------------------------------------------
    const priorKeyRecord = await this.deps.idempotencyKeyRepository.findByKey(
      input.idempotencyKey,
      tenant,
    );

    // ------------------------------------------------------------------
    // 4. Fingerprint equivalence check (pre-transaction read)
    // ------------------------------------------------------------------
    const equivalent = await this.deps.metadataRepository.findEquivalent(
      { agendaDate, fingerprint },
      tenant,
    );

    if (equivalent !== null) {
      // Here equivalent exists → return ALREADY_IMPORTED (no new state, no audit).
      //
      // Metrics semantics for ALREADY_IMPORTED:
      //   receivedRecords = 0  — no records were processed in this attempt.
      //   All other counters = 0.
      //   This satisfies the domain invariant:
      //     receivedRecords = processed + pendingReview + rejected + duplicateFolio
      //     0 = 0 + 0 + 0 + 0
      //   and:
      //     errors = rejected + duplicateFolio  →  0 = 0 + 0
      //
      // The caller who needs the outcome of the original import can retrieve it
      // via GET /agenda-imports/:id using the returned importacionId.
      const alreadyMetrics: ImportacionAgendaMetrics = {
        receivedRecords: 0,
        processed: 0,
        added: 0,
        updated: 0,
        unchanged: 0,
        restored: 0,
        pendingReview: 0,
        rejected: 0,
        duplicateFolio: 0,
        withdrawnFromAgenda: 0,
        incidents: 0,
        errors: 0,
      };
      return {
        importacionId: equivalent.importacionId.value,
        agendaDate: agendaDate.value,
        outcome: 'ALREADY_IMPORTED',
        metrics: alreadyMetrics,
        hasChanges: false,
      };
    }

    // If the same key was used before and it pointed to a DIFFERENT fingerprint → conflict
    if (priorKeyRecord !== null) {
      throw new ApplicationError(
        'IDEMPOTENCY_KEY_REUSED',
        'La Idempotency-Key ya fue utilizada con un artefacto de contenido distinto.',
      );
    }

    // ------------------------------------------------------------------
    // 5. Row-level processing (outside UoW — queries only)
    // ------------------------------------------------------------------
    const resolvedRows = await this.processRows(interpreted, context);

    // ------------------------------------------------------------------
    // 6. Transactional commit
    // ------------------------------------------------------------------
    const importacionId = ImportacionAgendaId.parse(randomUUID());
    const response = await this.deps.unitOfWork.execute(tenant, async (tx) => {
      const importacion = ImportacionAgenda.create({
        id: importacionId,
        agendaFecha: agendaDate,
        importedAt: tx.importedAt,
      });

      // ----------------------------------------------------------------
      // 6a. Track seen folios for duplicate detection within this import
      // ----------------------------------------------------------------
      const validCitaSnapshots: CitaSnapshot[] = [];
      const folioToRegistroId = new Map<string, RegistroImportadoAgendaId>();

      // First pass: build all RegistroImportadoAgenda and incidencias,
      // detecting DUPLICATE_FOLIO within the import batch.
      const finalResolvedRows: Array<{
        row: ResolvedRow;
        isDuplicate: boolean;
      }> = [];

      for (const resolved of resolvedRows) {
        const isDuplicate =
          resolved.folio !== null &&
          folioToRegistroId.has(resolved.folio.value);

        if (resolved.folio !== null && !isDuplicate) {
          folioToRegistroId.set(resolved.folio.value, resolved.registroId);
        }
        finalResolvedRows.push({ row: resolved, isDuplicate });
      }

      // Second pass: add registros and incidencias, collect valid CitaSnapshots
      for (const { row: resolved, isDuplicate } of finalResolvedRows) {
        const pos = PosicionRegistroOrigen.create(resolved.row.sourcePosition);
        const registro = RegistroImportadoAgenda.create({
          id: resolved.registroId,
          sourcePosition: pos,
          originalValues: resolved.row.originalValues,
          interpretedValues: resolved.row.interpretedValues,
          resolvedReferences: {
            expedienteId: resolved.citaSnapshot?.expedienteReference?.value ?? null,
            physicianReference: resolved.citaSnapshot?.medico
              ? resolved.citaSnapshot.medico.numeroEmpleado.value
              : null,
          },
        });
        importacion.addRegistro(registro);

        if (isDuplicate) {
          const incident = IncidenciaImportacion.create({
            id: IncidenciaImportacionId.parse(randomUUID()),
            registroId: resolved.registroId,
            sourcePosition: pos,
            type: 'DUPLICATE_FOLIO_IN_SNAPSHOT',
          });
          importacion.addIncidencia(incident);
          importacion.finalizeRegistro(resolved.registroId, 'DUPLICATE_FOLIO');
          continue;
        }

        // Add incidents from row processing
        for (const incident of resolved.incidents) {
          const inc = IncidenciaImportacion.create({
            id: IncidenciaImportacionId.parse(randomUUID()),
            registroId: resolved.registroId,
            sourcePosition: pos,
            type: incident.type as ImportIncident,
          });
          importacion.addIncidencia(inc);
        }

        // If record has pending incidents, finalize as PENDING_REVIEW or REJECTED now
        if (resolved.result !== null) {
          importacion.finalizeRegistro(resolved.registroId, resolved.result);
        } else if (resolved.citaSnapshot !== null) {
          // Will be finalized after reconciliation
          validCitaSnapshots.push(resolved.citaSnapshot);
        }
      }

      // ----------------------------------------------------------------
      // 6b. Load or create Agenda, then reconcile
      // ----------------------------------------------------------------
      const existingAgenda = await tx.agendaRepository.findByFecha(agendaDate, tenant);
      const agendaPreExisted = existingAgenda !== null;
      const agenda = existingAgenda ?? Agenda.create({ fecha: agendaDate });

      const reconciliation = agenda.reconcile({ incoming: validCitaSnapshots });

      // ----------------------------------------------------------------
      // 6c. Map reconciliation results back to registros
      // ----------------------------------------------------------------
      const addedFolios = new Set(reconciliation.added.map(f => f.value));
      const updatedFolios = new Set(reconciliation.updated.map(f => f.value));
      const unchangedFolios = new Set(reconciliation.unchanged.map(f => f.value));
      const restoredFolios = new Set(reconciliation.restored.map(f => f.value));

      for (const { row: resolved, isDuplicate } of finalResolvedRows) {
        if (isDuplicate || resolved.result !== null) {
          // Already finalized
          continue;
        }
        if (resolved.citaSnapshot === null || resolved.folio === null) {
          // Should not happen, but guard
          continue;
        }
        const folio = resolved.folio.value;
        let result: RecordProcessingResult;
        if (addedFolios.has(folio)) {
          result = 'ADDED';
        } else if (updatedFolios.has(folio)) {
          result = 'UPDATED';
        } else if (unchangedFolios.has(folio)) {
          result = 'UNCHANGED';
        } else if (restoredFolios.has(folio)) {
          result = 'RESTORED';
        } else {
          // Shouldn't happen if reconciliation is consistent
          result = 'UNCHANGED';
        }
        importacion.finalizeRegistro(resolved.registroId, result);
      }

      importacion.recordWithdrawnFromAgenda(reconciliation.withdrawn.length);

      // ----------------------------------------------------------------
      // 6d. Determine ImportOutcome
      // ----------------------------------------------------------------
      const hasReconciliationChanges =
        reconciliation.added.length > 0 ||
        reconciliation.updated.length > 0 ||
        reconciliation.restored.length > 0 ||
        reconciliation.withdrawn.length > 0;

      const outcome: ImportOutcome = (
        agendaPreExisted && hasReconciliationChanges ? 'RECONCILED' : 'IMPORTED'
      ) as ImportOutcome;

      importacion.finalize(outcome);

      // ----------------------------------------------------------------
      // 6e. Persist
      // ----------------------------------------------------------------
      await tx.importacionAgendaRepository.save(importacion, tenant);
      await tx.agendaRepository.save(agenda, tenant);

      // BUG-REIMPORT: Only register the fingerprint as "complete" when the import
      // has no rejected or pending-review records.
      //
      // If rejected > 0 or pendingReview > 0 the file was NOT fully processed —
      // registering the fingerprint would permanently block reimportation of the
      // same artifact even after fixing the underlying issue (parser bug, missing
      // reference data, etc.).
      //
      // When the fingerprint is NOT registered the next import of the same file
      // will re-process ALL rows.  Rows that were previously successful are safe:
      //   - reconcile() sees their folio in `citas` → UNCHANGED / UPDATED
      //   - PostgresAgendaRepository.save() uses ON CONFLICT DO UPDATE (no duplicates)
      //
      // Once a reimport finally produces zero rejected/pending records the
      // fingerprint IS registered and subsequent imports return ALREADY_IMPORTED.
      const importMetrics = importacion.metrics!;
      const hasIncompleteRecords =
        importMetrics.rejected > 0 || importMetrics.pendingReview > 0;

      if (!hasIncompleteRecords) {
        await tx.importArtifactMetadataRepository.associateConfirmedImport(
          { importacionId, agendaDate, fingerprint },
          tenant,
        );
      }

      await tx.idempotencyKeyRepository.recordKey(input.idempotencyKey, importacionId, tenant);

      // ----------------------------------------------------------------
      // 6f. Audit success
      // ----------------------------------------------------------------
      const successEntry: AuditEntry = {
        action: 'AGENDA_IMPORT',
        resourceType: 'AGENDA_IMPORT',
        resourceId: importacion.id.value,
        result: 'success',
      };
      await tx.auditWriter.append(successEntry, context);

      // ----------------------------------------------------------------
      // 6g. Build response
      // ----------------------------------------------------------------
      const metrics = importacion.metrics!;
      const hasChanges =
        outcome !== 'ALREADY_IMPORTED' &&
        metrics.added + metrics.updated + metrics.restored + metrics.withdrawnFromAgenda > 0;

      return {
        importacionId: importacion.id.value,
        agendaDate: agendaDate.value,
        outcome,
        metrics,
        hasChanges,
      } satisfies ImportAgendaResponse;
    });

    return response;
  }

  // ---------------------------------------------------------------------------
  // Row processing (outside transaction — only queries)
  // ---------------------------------------------------------------------------

  private async processRows(
    interpreted: InterpretedAgendaFile,
    context: RequestContext,
  ): Promise<ResolvedRow[]> {
    const { tenant } = context;
    const results: ResolvedRow[] = [];

    for (const row of interpreted.rows) {
      const registroId = RegistroImportadoAgendaId.parse(randomUUID());
      const iv = row.interpretedValues;
      const ov = row.originalValues;

      // ------------------------------------------------------------------
      // Required field validation
      // ------------------------------------------------------------------
      if (
        iv.folio === null ||
        iv.agendaFecha === null ||
        iv.appointmentTime === null ||
        iv.numeroEmpleado === null ||
        iv.servicioEspecialidad === null ||
        iv.appointmentKind === null ||
        iv.beneficiaryType === null
      ) {
        results.push({
          row,
          registroId,
          folio: iv.folio,
          citaSnapshot: null,
          incidents: [{ type: 'REQUIRED_DATA_MISSING' }],
          result: 'REJECTED',
        });
        continue;
      }

      // ------------------------------------------------------------------
      // Parse HoraCita
      // ------------------------------------------------------------------
      let hora: HoraCita;
      try {
        hora = HoraCita.parse(iv.appointmentTime);
      } catch {
        results.push({
          row,
          registroId,
          folio: iv.folio,
          citaSnapshot: null,
          incidents: [{ type: 'REQUIRED_DATA_MISSING' }],
          result: 'REJECTED',
        });
        continue;
      }

      // ------------------------------------------------------------------
      // Médico resolution
      // ------------------------------------------------------------------
      const medicoResolution: MedicoResolution =
        await this.deps.medicoQuery.findByEmployeeNumber(iv.numeroEmpleado, tenant);

      let resolvedMedico: MedicoReferencia | null = null;
      const incidents: Array<{ type: string }> = [];

      if (medicoResolution.kind === 'RESOLVED') {
        resolvedMedico = medicoResolution.medico;
      } else if (medicoResolution.kind === 'NOT_FOUND') {
        // Try controlled fallback if original name is available
        const fallbackName = ov.physicianName;
        if (fallbackName !== null) {
          const fallback = await this.deps.medicoQuery.findControlledFallback(fallbackName, tenant);
          if (fallback.kind === 'RESOLVED') {
            resolvedMedico = fallback.medico;
          } else if (fallback.kind === 'AMBIGUOUS') {
            incidents.push({ type: 'PHYSICIAN_AMBIGUOUS' });
          } else {
            incidents.push({ type: 'PHYSICIAN_NOT_RESOLVED' });
          }
        } else {
          incidents.push({ type: 'PHYSICIAN_NOT_RESOLVED' });
        }
      } else {
        // AMBIGUOUS from primary lookup
        incidents.push({ type: 'PHYSICIAN_AMBIGUOUS' });
      }

      if (resolvedMedico === null) {
        results.push({
          row,
          registroId,
          folio: iv.folio,
          citaSnapshot: null,
          incidents,
          result: 'PENDING_REVIEW',
        });
        continue;
      }

      // ------------------------------------------------------------------
      // Expediente resolution (0..N — no incident, null ref acceptable)
      // ------------------------------------------------------------------
      let expedienteReference: ExpedienteReferencia | null = null;
      if (ov.expedienteReference !== null) {
        try {
          const matches = await this.deps.expedienteQuery.resolve(
            { expedienteNumero: ov.expedienteReference },
            tenant,
          );
          if (matches.length === 1) {
            expedienteReference = matches[0].reference;
          }
          // 0 or N>1 → null (per spec, no incident required)
        } catch {
          // resolution error → null reference, continue processing
        }
      }

      // ------------------------------------------------------------------
      // Build CitaSnapshot
      // ------------------------------------------------------------------
      const citaSnapshot: CitaSnapshot = {
        folio: iv.folio,
        agendaFecha: iv.agendaFecha,
        hora,
        expedienteReference,
        nombrePaciente: ov.patientName ?? '',
        tipoDerechohabiente: iv.beneficiaryType,
        tipoConsulta: iv.appointmentKind,
        medico: resolvedMedico,
        servicioEspecialidad: iv.servicioEspecialidad,
      };

      results.push({
        row,
        registroId,
        folio: iv.folio,
        citaSnapshot,
        incidents: [],
        result: null, // will be mapped after reconciliation
      });
    }

    return results;
  }
}
